[book]
authors = ["Keno Omu"]
language = "en"
multilingual = false
src = "src"
title = "Optimizing Your Learning"

[build]
build-dir = "output"
create-missing = false
use-default-preprocessors = false
